#set the room for the bot to post in.  Bot (and you) should be members of this room
room: Public Room Name  # name of some room here on symphony or teams.
server:
  port: 8080

# include if using symphony
bdk:
  host: develop.symphony.com #your pod id.
  bot:
    username: symphony.practice.bot1 # bot id
    privateKey:  
      path: private-key.pem # bot private key

# include if using teams
teams:
  storage:
    type: blob
    connection-string: # blob storage details
  app:
    tennantId: # tennant id for teams instance
  bot:
    MicrosoftAppPassword: # bot password
    MicrosoftAppId: # bot app id

spring:
  profiles:
    active: teams, symphony  # comment these if you only want a single platform